name: Organization CI

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  DOTNET_VERSION: '10.0.303'
  SOLUTION_FILE: 'TexasMediaDart.Organization.slnx'
  DATABASE_PROJECT: 'database/TexasMediaDart.Organization.Database/TexasMediaDart.Organization.Database.sqlproj'

jobs:
  build:
    name: Build Organization Service
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Display .NET information
        run: dotnet --info

      - name: Restore .NET solution
        run: dotnet restore ${{ env.SOLUTION_FILE }}

      - name: Build .NET solution
        run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore

      - name: Restore database project
        run: dotnet restore ${{ env.DATABASE_PROJECT }}

      - name: Build database project
        run: dotnet build ${{ env.DATABASE_PROJECT }} --configuration Release --no-restore